package main

type MimeTypes = map[string]string

var mimes = MimeTypes{
	".css":         "text/css; charset=utf-8",
	".csv":         "text/csv; charset=utf-8",
	".md":          "text/markdown; charset=utf-8",
	".markdown":    "text/markdown; charset=utf-8",
	".htm":         "text/html; charset=utf-8",
	".html":        "text/html; charset=utf-8",
	".shtml":       "text/html; charset=utf-8",
	".xml":         "text/xml; charset=utf-8",
	".txt":         "text/plain; charset=utf-8",
	".js":          "text/javascript; charset=utf-8",
	".mjs":         "text/javascript; charset=utf-8",
	".xhtml":       "application/xhtml+xml; charset=utf-8",
	".json":        "application/json; charset=utf-8",
	".map":         "application/json; charset=utf-8",
	".webmanifest": "application/manifest+json; charset=utf-8",
	".pdf":         "application/pdf",
	".wasm":        "application/wasm",
	".webapp":      "application/x-web-app-manifest+json; charset=utf-8",
	".appcache":    "text/cache-manifest; charset=utf-8",
	".gif":         "image/gif",
	".jpeg":        "image/jpeg",
	".jpg":         "image/jpeg",
	".png":         "image/png",
	".apng":        "image/apng",
	".avif":        "image/avif",
	".avifs":       "image/avif-sequence",
	".webp":        "image/webp",
	".svg":         "image/svg+xml; charset=utf-8",
	".ico":         "image/x-icon",
	".woff":        "font/woff",
	".woff2":       "font/woff2",
	".eot":         "application/vnd.ms-fontobject",
	".ttf":         "font/ttf",
	".ttc":         "font/collection",
	".otf":         "font/otf",
}
